source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CDAPdfReader_Example', :exclusive => true do
  pod "CDAPdfReader", :path => "../"
end

target 'CDAPdfReader_Tests', :exclusive => true do
  pod "CDAPdfReader", :path => "../"

  pod 'Kiwi'
end
